### ISSUE TITLE
Support later versions of Jane PHP package to allow latest major version of symfony/options-resolver

### ISSUE THREAD

**Issue by GaryJones** [10up/wpacceptance#22]
**Is your enhancement related to a problem? Please describe.**

`jane-php/open-api-runtime` was [pinned](https://github.com/10up/wpacceptance/commit/41f51fd6ee09fcf84a30db82915bc03c928b6520) to a specific 4.2.0 to avoid a bug in a later version. This version [uses](https://github.com/janephp/open-api-runtime/blob/v4.2.0/composer.json#L23) `symfony/options-resolver` `^3.1|^4.0`, but that package is now on v5.

**Describe the solution you'd like**

`jane-php/open-api-runtime` 5.2.2 supports using `symfony/options-resolver` ^5.0, so can wpacceptance update the version of `jane-php/open-api-runtime` that it supports to include this? (`^5.2.2` or `4.2.0 | ^5.2.2` or similar).

The plugin I want to use wpacceptance in already has symfony/options-resolver 5 installed, and while I will remove the vendor directory and do a full re-install and end up with options-resolver 4, I'm not seeing a good reason to have wpacceptance be stuck on an old version of the jane-php dependency anyway :-)

**Comment by tlovett1** [comment]
@GaryJones would love to see a PR here :) Excited you are using the project.
